[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#2C3E50"
font = "sans serif"

[server]
maxUploadSize = 10
port = 8501

[browser]
gatherUsageStats = false